version: '3.8'

services:
  api:
    container_name: gym-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    env_file:
      - .env

# TODO: Add postgresql service