spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Config
jwt.secret.key=Y2xhdmUtc3VwZXItc2VjcmV0YS1wYXJhLXRva2Vucy1jb24taHM1MTItZW4tbWktYXBsaWNhY2lvbi1iYWNrZW5kLTEyMzQ1Ngo=

# JWT Expirations (milisegundos)
jwt.access.expiration=900000
jwt.refresh.expiration=3600000

# Logging
logging.level.root=INFO

# Spring Boot Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Info endpoint customization
info.app.name=GYM API
info.app.version=1.0.0
info.app.description=API for client and membership management of gym
