#.env files are not supported in the local environment. Use system environment variables or replace the values directly.

# Configure your database URL, username, and password
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configure your secret key and the expiration times for access and refresh tokens
jwt.secret.key=${JWT_SECRET_KEY}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

# Configure your WhatsApp ID and access token
whatsapp.identification=${WHATSAPP_IDENTIFICATION}
whatsapp.token=${WHATSAPP_TOKEN}

# Logging
logging.level.root=INFO

# Spring Boot Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Info endpoint customization
info.app.name=GYM API
info.app.version=1.0.0
info.app.description=API for clients and memberships management of gym