package com.project.gym.entity.enums;

public enum ApiError
{
    INVALID_PASSWORD,
    METHOD_ARGUMENT_MISMATCH,
    METHOD_ARGUMENT_NOT_VALID,
    HTTP_MESSAGE_NOT_READABLE,

    COOKIE_NOT_FOUND,
    INVALID_TOKEN,

    BAD_CREDENTIALS,
    ACCESS_DENIED,
    USER_ALREADY_AUTHENTICATED,

    MEMBERSHIP_NOT_FOUND,
    USERNAME_NOT_FOUND,

    INVALID_MEMBERSHIP_ASSIGNMENT,
    PHONE_NUMBER_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,

    GENERIC,
}
