package com.project.gym.entity.enums;


public enum Permission
{
    ROLE_UPDATE,
    ADMIN_READ,
    STAFF_READ, STAFF_UPDATE, STAFF_DELETE,
    USER_READ, USER_UPDATE, USER_DELETE,
    MEMBERSHIP_CREATE, MEMBERSHIP_READ, MEMBERSHIP_UPDATE, MEMBERSHIP_DELETE;
}
